config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"
  get '/signup', to: "users#new", as: "signup"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/popular', to: "cocktails#popular"
  get '/others', to: "users#others"

  post '/spirits/search', to: "spirits#search", as: "search"

  resources :users do
    resources :recipes, only: [:new, :create]
  end

  resources :spirits do
    resources :recipes, only: [:index]
  end

  # put actions for voting
  resources :recipes do
    member do
      put "like", to: "recipes#upvote"
      put "dislike", to: "recipes#downvote"
    end
  end

  # cocktails/2/recipes/new #=> Add a recipe to THIS Cocktail (new)
    # (then redirect to cocktail_path(cocktail))
  resources :cocktails do
    resources :recipes, only: [:new, :create, :index]
  end

  # resources :recipes
  resources :users
  resources :sessions
  resources :cocktails
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :recipes, dependent: :destroy
    has_many :users, through: :recipes
    belongs_to :spirit
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @cocktails = Cocktail.all
    end

    def show
        if Cocktail.find_by(id: params[:id]) == nil
            flash[:message] = "This cocktail does not exist"
            redirect_to cocktails_path
        else
            @cocktail = Cocktail.find_by(id: params[:id])
            @user_recipes = @cocktail.recipes.all_by_user(current_user)
            @other_recipes = @cocktail.recipes.all_except_user(current_user)
        end
    end

    def popular 
        @recipes = Recipe.highest_rated_recipes
    end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper

end

app/views/cocktails/index.html.erb
<h1><i>All Cocktails</i></h1>
<br>


<ol id="list">
            <% @cocktails.each do |cocktail| %>
                <% if cocktail.recipes.any? %>
                    <h4><li><i><%= link_to cocktail.spirit.name + " Cocktails:", spirit_recipes_path(cocktail.spirit) %></i>
                    <br><br>
                    <ul>
                        <li><i><%= link_to cocktail.name, cocktail_path(cocktail) %></i></li><br>
                    </ul>
                    </li></h4>
                <% end %>
            <% end %>
</ol>

app/views/cocktails/popular.html.erb
<h1>Most Popular Recipes</h1>

<ol>
<% @recipes.each do |r| %>
    <li><%= link_to r.name, cocktail_path(r.cocktail)%> by <%= link_to r.user.username, user_path(r.user) %><br>
    <i>Ingredients:</i> <%= r.ingredients %><br>
    <i>Garnish:</i> <%= r.garnish %><br>
    <i>Notes:</i> <%= r.notes %></li><br>
    <% if r.user != current_user %>
        <div class="vote">
            <strong>Vote: </strong>
            <%= button_to '↑', like_recipe_path(r), method: :put, id: "vote-up" %>
            <%= button_to '↓', dislike_recipe_path(r), method: :put, id: "vote-down" %>
        </div>
    <% else %>
        <%= button_to 'Edit', edit_recipe_path(r), method: 'get', class: "crud_button" %>
        <%= button_to 'Delete', recipe_path(r), method: 'delete', data: { confirm: 'Are you sure?' }, class: "crud_button" %>
    <% end %><br><br></li>
<% end %>
</ol>

app/views/cocktails/show.html.erb
<h1><i>The <%= @cocktail.name %> (<%= @cocktail.spirit.name %>)</i></h1>

<% if @user_recipes.exists? %>
    <h3><i>Your <%= pluralize_without_count(@user_recipes.size, "Recipe") %>:</i></h3>
    <% @user_recipes.each_with_index do |r, i| %>
        <div class="user_recipe">
        <strong><i>Variation #<%= i + 1 %>:</i></strong><br>
        <% if Recipe.highest_rated_recipes.include?(r) %>
            <strong>* Popular Recipe *</strong><br>
        <% end %>
        <i>Ingredients:</i> <%= r.ingredients %><br>
        <i>Garnish:</i> <%= r.garnish %><br>
        <i>Notes:</i> <%= r.notes %></li><br><br>
        
        <%= button_to 'Edit', edit_recipe_path(r), method: 'get', class: "crud_button" %>
        <%= button_to 'Delete', recipe_path(r), method: 'delete', data: { confirm: 'Are you sure?' }, class: "crud_button" %>
        </div>            
        <br><br>
    <% end %>
<% end %>

<% if @other_recipes.exists? %>
    <h3>Other Users' Recipes: </h3>
    <ol>
        <% @other_recipes.each do |recipe| %>
            <li><%= link_to recipe.user.username, user_path(recipe.user) %>'s Recipe:<br><br>
            <% if Recipe.highest_rated_recipes.include?(recipe) %>
                <strong>* Popular Recipe *</strong><br>
            <% end %>
            <i>Ingredients:</i> <%= recipe.ingredients %><br>
            <i>Garnish:</i> <%= recipe.garnish %><br>
            <i>Notes:</i> <%= recipe.notes %></li><br>
            <div class="vote">
                <strong>Vote: </strong>
                <%= button_to '↑', like_recipe_path(recipe), method: :put, id: "vote-up" %>
                <%= button_to '↓', dislike_recipe_path(recipe), method: :put, id: "vote-down" %>
            </div>
        <% end %>
    </ol>
<% end %>
<div id="new-link-container">
    <h4><i><%= link_to "Add a Recipe to this Cocktail", new_cocktail_recipe_path(@cocktail), id: "new-link" %></i></h4>
    <br><br><br><br>
</div>