config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"
  get '/signup', to: "users#new", as: "signup"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/popular', to: "cocktails#popular"
  get '/others', to: "users#others"

  post '/spirits/search', to: "spirits#search", as: "search"

  resources :users do
    resources :recipes, only: [:new, :create]
  end

  resources :spirits do
    resources :recipes, only: [:index]
  end

  # put actions for voting
  resources :recipes do
    member do
      put "like", to: "recipes#upvote"
      put "dislike", to: "recipes#downvote"
    end
  end

  # cocktails/2/recipes/new #=> Add a recipe to THIS Cocktail (new)
    # (then redirect to cocktail_path(cocktail))
  resources :cocktails do
    resources :recipes, only: [:new, :create, :index]
  end

  # resources :recipes
  resources :users
  resources :sessions
  resources :cocktails
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :cocktails, through: :recipes
    validates :username, presence: true, uniqueness: true
    has_secure_password
    scope :other_users, ->(user) { where.not("id = ?", user.id) }
    acts_as_voter

    def self.from_omniauth(auth)
        where(username: auth.info.name).first_or_initialize do |user|
          user.username = auth.info.name
          user.password = SecureRandom.hex
        end
    end

    def self.users_from_recipes(recipes_array)
        recipes_array.map{|recipe| recipe.user}.uniq
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def others
        @users = User.other_users(current_user)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        if @user = User.find_by(id: params[:id])
            @recipes = @user.recipes
        else
            flash[:message] = "This user does not exist."
            redirect_to recipes_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="container">
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br><br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit "Sign Up", class:"crud_button" %>
<% end %>
<br>
<%= link_to "Log In with Google", '/auth/google_oauth2', id: "google" %>
<br><br>
<%= link_to "Home", root_path, class: "session" %>
<br>
<%= link_to "Login", login_path, class: "session" %>
</div>

app/views/users/others.html.erb
<h1>Other Users' Recipes</h1>
<% @users.each do |u| %>
    <% if !u.recipes.empty? %>
        <h3><%= link_to u.username, user_path(u) %>'s Recipes</h3>
        <ol>
        <% u.recipes.each do |r| %>
            <% if Recipe.highest_rated_recipes.include?(r) %>
                <strong>* Popular Recipe *</strong><br><br>
            <% end %>
            <li><strong><%= link_to r.name, cocktail_path(r.cocktail) %></strong><br>
            <i>Ingredients:</i> <%= r.ingredients %><br>
            <i>Garnish:</i> <%= r.garnish %><br>
            <i>Notes:</i> <%= r.notes %></li><br>

            <div class="vote">
                <strong>Vote: </strong>
                <%= button_to '↑', like_recipe_path(r), method: :put, id: "vote-up" %>
                <%= button_to '↓', dislike_recipe_path(r), method: :put, id: "vote-down" %>
            </div><br><br>
        <% end %>    
        </ol>
    <% end %>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user && !@user.recipes.empty? %>
    <h1><i>Your Recipes</i></h1>
<% elsif @user == current_user && @user.recipes.empty? %>
    <h1><i><%= link_to "Add a New Recipe!", new_recipe_path %></i></h1>
<% else %>
    <h1><i><%= @user.username %>'s Recipes</i></h1>
<% end %>

<ol>
    <% @user.recipes.each do |r| %>
        <% if Recipe.highest_rated_recipes.include?(r) %>
                <strong>* Popular Recipe *</strong><br><br>
        <% end %>
        <li><i><%= link_to r.name, cocktail_path(r.cocktail) %></i><br><br>
        <i>Ingredients:</i> <%= r.ingredients %><br>
        <i>Garnish:</i> <%= r.garnish %><br>
        <i>Notes:</i> <%= r.notes %></li><br>
        <% if r.user != current_user %>
            <div class="vote">
                <strong>Vote: </strong>
                <%= button_to '↑', like_recipe_path(r), method: :put, id: "vote-up" %>
                <%= button_to '↓', dislike_recipe_path(r), method: :put, id: "vote-down" %>
            </div>
        <% else %>
        <%= button_to 'Edit', edit_recipe_path(r), method: 'get', class: "crud_button" %>
        <%= button_to 'Delete', recipe_path(r), method: 'delete', data: { confirm: 'Are you sure?' }, class: "crud_button" %>
        <% end %><br><br>
    <% end %>
</ol>