config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"
  get '/signup', to: "users#new", as: "signup"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/popular', to: "cocktails#popular"
  get '/others', to: "users#others"

  post '/spirits/search', to: "spirits#search", as: "search"

  resources :users do
    resources :recipes, only: [:new, :create]
  end

  resources :spirits do
    resources :recipes, only: [:index]
  end

  # put actions for voting
  resources :recipes do
    member do
      put "like", to: "recipes#upvote"
      put "dislike", to: "recipes#downvote"
    end
  end

  # cocktails/2/recipes/new #=> Add a recipe to THIS Cocktail (new)
    # (then redirect to cocktail_path(cocktail))
  resources :cocktails do
    resources :recipes, only: [:new, :create, :index]
  end

  # resources :recipes
  resources :users
  resources :sessions
  resources :cocktails
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarTalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:message] %>
    <h4 style="color:red;"><%= flash[:message] %></h4>
  <% elsif flash[:success] %>
    <h4 style="color:green;"><%= flash[:success] %></h4>
  <% end %>
  <%= content_tag :div, @error, style: "color:red;" %>
  
  <% if logged_in? %>
    <ul class="nav">
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "New Recipe", new_user_recipe_path(current_user) %></li>
        <li><%= link_to "All Cocktails", cocktails_path %></li>
        <li>
          <%= form_tag('/spirits/search') do %>
            <%= search_field_tag 'Search' %>
          <% end %>
        </li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <li><%= link_to "Highest Rated", popular_path %></li>
        <li><%= link_to "Other Users' Recipes", others_path %></li>
        <li><%= link_to "Logout", logout_path, method:"delete" %></li>
    </ul>
  <% end %>
  <br>
    <%= yield %>
  </body>
</html>